version: '2'

services:
  front:
    build: .
    working_dir: /var/www/app
    container_name: eric-frontend
    command: bash -c 'npm i && npm run dev'
    volumes:
      - ./:/var/www/app:cached
      - ./node_modules:/var/www/app/node_modules:cached
    ports:
      - 80:8080
